/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
    export interface Resource {
        API: {
            type: 'sst.aws.ApiGatewayV2';
            url: string;
        };
        Todos: {
            name: string;
            type: 'sst.aws.Dynamo';
        };
        WebApp: {
            type: 'sst.aws.StaticSite';
            url: string;
        };
    }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
