/* tslint:disable */
/* eslint-disable */
/**
 * TODO API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PasswordRequiredError
 */
export interface PasswordRequiredError {
    /**
     *
     * @type {boolean}
     * @memberof PasswordRequiredError
     */
    isProtected: boolean;
}

/**
 * Check if a given object implements the PasswordRequiredError interface.
 */
export function instanceOfPasswordRequiredError(
    value: object,
): value is PasswordRequiredError {
    if (!('isProtected' in value) || value['isProtected'] === undefined)
        return false;
    return true;
}

export function PasswordRequiredErrorFromJSON(
    json: any,
): PasswordRequiredError {
    return PasswordRequiredErrorFromJSONTyped(json, false);
}

export function PasswordRequiredErrorFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PasswordRequiredError {
    if (json == null) {
        return json;
    }
    return {
        isProtected: json['isProtected'],
    };
}

export function PasswordRequiredErrorToJSON(json: any): PasswordRequiredError {
    return PasswordRequiredErrorToJSONTyped(json, false);
}

export function PasswordRequiredErrorToJSONTyped(
    value?: PasswordRequiredError | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        isProtected: value['isProtected'],
    };
}
