/* tslint:disable */
/* eslint-disable */
/**
 * TODO API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TodoListItem
 */
export interface TodoListItem {
    /**
     *
     * @type {string}
     * @memberof TodoListItem
     */
    text: string;
    /**
     *
     * @type {boolean}
     * @memberof TodoListItem
     */
    completed: boolean;
}

/**
 * Check if a given object implements the TodoListItem interface.
 */
export function instanceOfTodoListItem(value: object): value is TodoListItem {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('completed' in value) || value['completed'] === undefined)
        return false;
    return true;
}

export function TodoListItemFromJSON(json: any): TodoListItem {
    return TodoListItemFromJSONTyped(json, false);
}

export function TodoListItemFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): TodoListItem {
    if (json == null) {
        return json;
    }
    return {
        text: json['text'],
        completed: json['completed'],
    };
}

export function TodoListItemToJSON(json: any): TodoListItem {
    return TodoListItemToJSONTyped(json, false);
}

export function TodoListItemToJSONTyped(
    value?: TodoListItem | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        text: value['text'],
        completed: value['completed'],
    };
}
