/* tslint:disable */
/* eslint-disable */
/**
 * TODO API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TodoListItem } from './TodoListItem.js';
import { TodoListItemFromJSON, TodoListItemToJSON } from './TodoListItem.js';

/**
 *
 * @export
 * @interface TodoList
 */
export interface TodoList {
    /**
     *
     * @type {string}
     * @memberof TodoList
     */
    id: string;
    /**
     *
     * @type {Array<TodoListItem>}
     * @memberof TodoList
     */
    list: Array<TodoListItem>;
    /**
     * Whether this list currently has a password set. Only meaningful in responses; ignored if sent in a request.
     * @type {boolean}
     * @memberof TodoList
     */
    isProtected?: boolean;
    /**
     * Only used when updating a list. Set to a non-empty string to protect the list or change its password, to null or an empty string to remove password protection, or omit to leave protection unchanged. Never returned in responses.
     * @type {string}
     * @memberof TodoList
     */
    password?: string | null;
}

/**
 * Check if a given object implements the TodoList interface.
 */
export function instanceOfTodoList(value: object): value is TodoList {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('list' in value) || value['list'] === undefined) return false;
    return true;
}

export function TodoListFromJSON(json: any): TodoList {
    return TodoListFromJSONTyped(json, false);
}

export function TodoListFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): TodoList {
    if (json == null) {
        return json;
    }
    return {
        id: json['id'],
        list: (json['list'] as Array<any>).map(TodoListItemFromJSON),
        isProtected:
            json['isProtected'] == null ? undefined : json['isProtected'],
        password: json['password'] == null ? undefined : json['password'],
    };
}

export function TodoListToJSON(json: any): TodoList {
    return TodoListToJSONTyped(json, false);
}

export function TodoListToJSONTyped(
    value?: TodoList | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value['id'],
        list: (value['list'] as Array<any>).map(TodoListItemToJSON),
        isProtected: value['isProtected'],
        password: value['password'],
    };
}
