/* tslint:disable */
/* eslint-disable */
/**
 * TODO API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    TodoListFromJSON,
    TodoListToJSON,
    type TodoList,
} from '../models/TodoList.js';
import * as runtime from '../runtime.js';

export interface TodosIdGetRequest {
    id: string;
    xTodoPassword?: string;
}

export interface TodosIdPutRequest {
    id: string;
    todoList: TodoList;
    xTodoPassword?: string;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
    /**
     * Creates request options for todosIdGet without sending the request
     */
    async todosIdGetRequestOpts(
        requestParameters: TodosIdGetRequest,
    ): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling todosIdGet().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTodoPassword'] != null) {
            headerParameters['X-Todo-Password'] = String(
                requestParameters['xTodoPassword'],
            );
        }

        let urlPath = `/todos/{id}`;
        urlPath = urlPath.replace(
            '{id}',
            encodeURIComponent(String(requestParameters['id'])),
        );

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets the TODO list.
     */
    async todosIdGetRaw(
        requestParameters: TodosIdGetRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<TodoList>> {
        const requestOptions =
            await this.todosIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            TodoListFromJSON(jsonValue),
        );
    }

    /**
     * Gets the TODO list.
     */
    async todosIdGet(
        requestParameters: TodosIdGetRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<TodoList> {
        const response = await this.todosIdGetRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     * Creates request options for todosIdPut without sending the request
     */
    async todosIdPutRequestOpts(
        requestParameters: TodosIdPutRequest,
    ): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling todosIdPut().',
            );
        }

        if (requestParameters['todoList'] == null) {
            throw new runtime.RequiredError(
                'todoList',
                'Required parameter "todoList" was null or undefined when calling todosIdPut().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xTodoPassword'] != null) {
            headerParameters['X-Todo-Password'] = String(
                requestParameters['xTodoPassword'],
            );
        }

        let urlPath = `/todos/{id}`;
        urlPath = urlPath.replace(
            '{id}',
            encodeURIComponent(String(requestParameters['id'])),
        );

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TodoListToJSON(requestParameters['todoList']),
        };
    }

    /**
     * Updates the TODO list.
     */
    async todosIdPutRaw(
        requestParameters: TodosIdPutRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<TodoList>> {
        const requestOptions =
            await this.todosIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            TodoListFromJSON(jsonValue),
        );
    }

    /**
     * Updates the TODO list.
     */
    async todosIdPut(
        requestParameters: TodosIdPutRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<TodoList> {
        const response = await this.todosIdPutRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }
}
